//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CVGS.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CVGSAppEntities : DbContext
    {
        public CVGSAppEntities()
            : base("name=CVGSAppEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CreditCard> CreditCards { get; set; }
        public virtual DbSet<GameCategory> GameCategories { get; set; }
        public virtual DbSet<GamePlatform> GamePlatforms { get; set; }
        public virtual DbSet<Province> Provinces { get; set; }
        public virtual DbSet<MemberUser> MemberUsers { get; set; }
        public virtual DbSet<Game> Games { get; set; }
        public virtual DbSet<GameRating> GameRatings { get; set; }
        public virtual DbSet<GameReview> GameReviews { get; set; }
        public virtual DbSet<UserCartItem> UserCartItems { get; set; }
        public virtual DbSet<Order> Orders { get; set; }
        public virtual DbSet<OrderItem> OrderItems { get; set; }
        public virtual DbSet<FriendList> FriendLists { get; set; }
        public virtual DbSet<WishList> WishLists { get; set; }
        public virtual DbSet<Event> Events { get; set; }
        public virtual DbSet<EventAttendee> EventAttendees { get; set; }
    }
}
