//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CVGS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Event
    {
        public string Id { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public System.DateTime StartTime { get; set; }
        public System.DateTime EndTime { get; set; }
        public int AttendeeNumber { get; set; }
        public int MaxAttendeeNumber { get; set; }
        public bool IsIRL { get; set; }
        public string Location { get; set; }
    }
}
