//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CVGS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class MemberUser
    {
        public string Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public Nullable<int> Sex { get; set; }
        public System.DateTime BirthDate { get; set; }
        public Nullable<bool> SendPromotionalEmails { get; set; }
        public Nullable<int> CategoryOptions { get; set; }
        public Nullable<int> PlatformOptions { get; set; }
        public string MailingAddressApartment { get; set; }
        public string MailingAddressStreetNumber { get; set; }
        public string MailingAddressStreetName { get; set; }
        public string MailingAddressCity { get; set; }
        public string MailingAddressProvince { get; set; }
        public string MailingAddressPostalCode { get; set; }
        public string ShippingAddressApartment { get; set; }
        public string ShippingAddressStreetNumber { get; set; }
        public string ShippingAddressStreetName { get; set; }
        public string ShippingAddressCity { get; set; }
        public string ShippingAddressProvince { get; set; }
        public string ShippingAddressPostalCode { get; set; }
    }
}
