//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CVGS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public string Id { get; set; }
        public string UserId { get; set; }
        public System.DateTime PurchaseDate { get; set; }
        public string CreditCardUsed { get; set; }
    }
}
